services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  web:
    build: .
    volumes:
      - .:/rails
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  postgres_volume: