services:
  db:
    image: postgres:17.4
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  # web-dev:
  #   build: .
  #   volumes:
  #     - .:/rails
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_HOST: db
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - db
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/rails
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      RAILS_MASTER_KEY: 657a5ea6faa2ca4b794d14957fb82555
    ports:
      - "80:80"
    depends_on:
      - db
volumes:
  postgres_volume: